<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ListaDeGestores.aspx.cs" Inherits="tp_integrador.ListaDeGestores" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
            background-color: #C0C0C0;
        }
        .auto-style2 {
            margin-left: 359px;
            margin-bottom: 67px;
        }
        .auto-style3 {
            width: 556px;
        }
        .auto-style4 {
            width: 752px;
        }
        .auto-style5 {
            width: 556px;
            height: 57px;
        }
        .auto-style6 {
            width: 752px;
            height: 57px;
        }
        .auto-style7 {
            height: 57px;
            width: 446px;
        }
        .auto-style8 {
            width: 446px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="auto-style1">
                <tr>
                    <td class="auto-style3">
                        <asp:Image ID="Image1" runat="server" CssClass="auto-style2" Height="350px" ImageUrl="~/Imagenes/logo.auto1.jpeg" Width="350px" />
                    </td>
                    <td class="auto-style4">
                        <h1>LISTADO DE GESTORES</h1>
                    </td>
                    <td class="auto-style8">
                        <asp:LinkButton ID="lbtnMaster" runat="server" PostBackUrl="~/MenuGestoriaMaster.aspx">Volver al Menu anterior</asp:LinkButton>
                    </td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style4">&nbsp;</td>
                    <td class="auto-style8">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style4">
                        <asp:GridView ID="grvgestores" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" BackColor="#CCCCCC" BorderColor="#999999" BorderStyle="Solid" BorderWidth="3px" CellPadding="4" CellSpacing="2" ForeColor="Black" OnRowCancelingEdit="grvgestores_RowCancelingEdit" OnRowDeleting="grvgestores_RowDeleting" OnRowEditing="grvgestores_RowEditing" OnRowUpdating="grvgestores_RowUpdating">
                            <Columns>
                                <asp:TemplateField HeaderText="Matricula">
                                    <EditItemTemplate>
                                        <asp:Label ID="lbl_eit_matricula" runat="server" Text='<%# Bind("matricula_ge") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_matricula" runat="server" Text='<%# Bind("matricula_ge") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="DNI">
                                    <EditItemTemplate>
                                        <asp:Label ID="lbl_eit_dni" runat="server" Text='<%# Bind("dni_ge") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_dni" runat="server" Text='<%# Bind("dni_ge") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Nombre">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_eit_nombre" runat="server" Text='<%# Bind("nombre_ge") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_nombre" runat="server" Text='<%# Bind("nombre_ge") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Apellido">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_eit_apellido" runat="server" Text='<%# Bind("apellido_ge") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_apellido" runat="server" Text='<%# Bind("apellido_ge") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Nacimiento">
                                    <EditItemTemplate>
                                        <asp:Label ID="lbl_eit_nacimiento" runat="server" Text='<%# Bind("nacimiento_ge") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_nacimiento" runat="server" Text='<%# Bind("nacimiento_ge") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Mail">
                                    <EditItemTemplate>
                                        <asp:Label ID="lbl_eit_mail" runat="server" Text='<%# Bind("mail_ge") %>'></asp:Label>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_mail" runat="server" Text='<%# Bind("mail_ge") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                                <asp:TemplateField HeaderText="Nombre de Perfil">
                                    <EditItemTemplate>
                                        <asp:TextBox ID="txt_eit_perfil" runat="server" Text='<%# Bind("nombre_perfil_ge") %>'></asp:TextBox>
                                    </EditItemTemplate>
                                    <ItemTemplate>
                                        <asp:Label ID="lbl_it_perfil" runat="server" Text='<%# Bind("nombre_perfil_ge") %>'></asp:Label>
                                    </ItemTemplate>
                                </asp:TemplateField>
                            </Columns>
                            <FooterStyle BackColor="#CCCCCC" />
                            <HeaderStyle BackColor="Black" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#CCCCCC" ForeColor="Black" HorizontalAlign="Left" />
                            <RowStyle BackColor="White" />
                            <SelectedRowStyle BackColor="#000099" Font-Bold="True" ForeColor="White" />
                            <SortedAscendingCellStyle BackColor="#F1F1F1" />
                            <SortedAscendingHeaderStyle BackColor="#808080" />
                            <SortedDescendingCellStyle BackColor="#CAC9C9" />
                            <SortedDescendingHeaderStyle BackColor="#383838" />
                        </asp:GridView>
                    </td>
                    <td class="auto-style8">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style4">&nbsp;</td>
                    <td class="auto-style8">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style5">
                        &nbsp;</td>
                    <td class="auto-style6">&nbsp;</td>
                    <td class="auto-style7"></td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
