<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PantallaModelo.aspx.cs" Inherits="tp_integrador.Pantalla_Modelo" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">

    .auto-style1 {
        width: 100%;
    }
    .auto-style2 {
        width: 1220px;
    }
    .auto-style3 {
        width: 506px;
    }
    .auto-style4 {
        width: 613px;
    }
        .auto-style5 {
            margin-left: 0px;
        }
        .auto-style6 {
            width: 855px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <table class="auto-style1">
                <tr>
                    <td class="auto-style6">
                        usuario:&nbsp;
                        <asp:Label ID="lblUsuario" runat="server"></asp:Label>
                        <br />
                        <asp:Label runat="server" ID="lblMsjError" Font-Bold="True" ForeColor="#FF0066" ></asp:Label> 
                    </td>
                    <td class="auto-style2">
                        <h1>Modelos</h1>
                        <p>&nbsp;</p>
                        <p>
                        <asp:Image ID="Image1" runat="server" ImageUrl="~/Imagenes/logo.jpeg" CssClass="auto-style5" />
                        </p>
                        <p>&nbsp;</p>
                    </td>
                    <td class="auto-style3">
                        &nbsp;</td>
                    <td class="auto-style4">
                        &nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style6">
                        <asp:HyperLink ID="hlkIngresarMO" runat="server" NavigateUrl="~/AgregarModelo.aspx">Ingresar un nuevo modelo</asp:HyperLink>
                    </td>
                    <td class="auto-style2">&nbsp;</td>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style4">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style6">
                        &nbsp;</td>
                    <td class="auto-style2">&nbsp;</td>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style4">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style6">
                        <asp:GridView ID="grdModelos" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" Height="433px" OnRowEditing="grdModelos_RowEditing" OnRowUpdating="grdModelos_RowUpdating" style="margin-right: 0px" Width="1093px" AutoGenerateColumns="False" OnRowCancelingEdit="grdModelos_RowCancelingEdit" OnRowDeleting="grdModelos_RowDeleting">
                            <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                            <Columns>
                            <%--   estos son solo para mostrarse       --%>
                            <asp:TemplateField HeaderText="Marca">
                                <EditItemTemplate>
                                    <asp:Label ID="lbl_edit_codma" runat="server" disabled Text='<%# Bind("cod_marca_mo") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblCodMarca" runat="server" Text='<%# Bind("cod_marca_mo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                             <asp:TemplateField HeaderText="Modelo">
                                <EditItemTemplate>
                                    <asp:Label ID="lbl_edit_modelo" runat="server" disabled Text='<%# Bind("cod_mo") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblModelo" runat="server" Text='<%# Bind("cod_mo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                             <asp:TemplateField HeaderText="Gamma">
                                <EditItemTemplate>
                                    <asp:Label ID="lbl_edit_gamma" runat="server" disabled Text='<%# Bind("cod_gamma_mo") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblGamma" runat="server" Text='<%# Bind("cod_gamma_mo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                                <%--   estos son para editar algunos datos--%>
                            <asp:TemplateField HeaderText="Nombre de Modelo">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txt_edit_nombreModelo" runat="server" Text='<%# Bind("nombre_mo") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblModeloNombre" runat="server" Text='<%# Bind("nombre_mo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                                  <asp:TemplateField HeaderText="Tipo de auto">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txt_edit_TipoAuto" runat="server" Text='<%# Bind("tipo_mo") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblTipoAuto" runat="server" Text='<%# Bind("tipo_mo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                                  <asp:TemplateField HeaderText="Cantidad de Puertas">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txt_edit_CantPuertas" runat="server" Text='<%# Bind("cant_puer_mo") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblCantPuertas" runat="server" Text='<%# Bind("cant_puer_mo") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                                  <asp:TemplateField HeaderText="Precio">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txt_edit_Precio" runat="server" Text='<%# Bind("precio") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblPrecio" runat="server" Text='<%# Bind("precio") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            </Columns>
                            <EditRowStyle BackColor="#999999" />
                            <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                            <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                            <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                            <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                            <SortedAscendingCellStyle BackColor="#E9E7E2" />
                            <SortedAscendingHeaderStyle BackColor="#506C8C" />
                            <SortedDescendingCellStyle BackColor="#FFFDF8" />
                            <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
                        </asp:GridView>
                    </td>
                    <td class="auto-style2">&nbsp;</td>
                    <td class="auto-style3">&nbsp;</td>
                    <td class="auto-style4">&nbsp;</td>
                </tr>
                <tr>
                    <td class="auto-style6">&nbsp;</td>
                    <td class="auto-style2">&nbsp;</td>
                    <td class="auto-style3">
                        <asp:Button ID="btnGestoria" runat="server" OnClick="Button1_Click" Text="volver al menu anterior" />
                    </td>
                    <td class="auto-style4">&nbsp;</td>
                </tr>
            </table>
        </div>
    </form>
</body>
</html>
