<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="PantallaMarcas.aspx.cs" Inherits="pantalla_modelos.menu_modelos" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
    <style type="text/css">
        .auto-style1 {
            width: 100%;
        }
        .auto-style2 {
            width: 386px;
        }
        .auto-style3 {
            height: 45px;
            width: 280px;
        }
        .auto-style4 {
            width: 386px;
            height: 45px;
        }
        .auto-style5 {
            height: 23px;
            width: 280px;
        }
        .auto-style6 {
            width: 386px;
            height: 23px;
            font-size: x-large;
        }
        .auto-style7 {
            height: 23px;
            width: 106px;
        }
        .auto-style8 {
            width: 106px;
        }
        .auto-style9 {
            height: 45px;
            width: 106px;
        }
        .auto-style10 {
            margin-left: 29px;
            margin-bottom: 0px;
        }
        .auto-style11 {
            width: 280px;
        }
        .auto-style12 {
            text-align: center;
        }
        .auto-style13 {
            width: 280px;
            height: 137px;
        }
        .auto-style14 {
            width: 386px;
            height: 137px;
        }
        .auto-style15 {
            width: 106px;
            height: 137px;
        }
    </style>
</head>
<body>
    <form id="form1" runat="server">
        <table class="auto-style1">
            <tr>
                <td class="auto-style5">Usuario:
                    <asp:Label ID="lblUsuario" runat="server"></asp:Label>
                    <br />
                    <asp:Label runat="server" ID="lblMsjError" Font-Bold="True" ForeColor="#FF0066" ></asp:Label> 
                </td>
                <td class="auto-style6">
                    <p class="auto-style12">
                        <strong>Menu Marcas</strong></p>
                </td>
                <td class="auto-style7">
                    <asp:Image ID="Image1" runat="server" CssClass="auto-style10" Height="300px" ImageUrl="~/Imagenes/logo.jpeg" />
                </td>
            </tr>
            <tr>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style8">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style3">
                    <asp:HyperLink ID="HLAgregarMarcas" runat="server" Font-Underline="True" ForeColor="#3333CC" NavigateUrl="~/AgregarMarca.aspx">Agregar Marcas al listado</asp:HyperLink>
                </td>
                <td class="auto-style4"></td>
                <td class="auto-style9"></td>
            </tr>
            <tr>
                <td class="auto-style13">
                    <asp:GridView ID="grdMarcas" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" AutoGenerateSelectButton="True" Height="16px" OnRowDeleting="grdMarcas_RowDeleting" OnRowEditing="grdMarcas_RowEditing" OnRowUpdating="grdMarcas_RowUpdating" Width="265px" OnRowCancelingEdit="grdMarcas_RowCancelingEdit" PageSize="3">
                        <Columns>
                            <asp:TemplateField HeaderText="Codigo de Marca">
                                <EditItemTemplate>
                                    <asp:Label ID="lbl_edit_codma" runat="server" Text='<%# Bind("cod_ma") %>'></asp:Label>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="lblCodMarca" runat="server" Text='<%# Bind("cod_ma") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                            <asp:TemplateField HeaderText="Nombre de Marca">
                                <EditItemTemplate>
                                    <asp:TextBox ID="txt_edit_nombremarca" runat="server" Text='<%# Bind("nombre_ma") %>'></asp:TextBox>
                                </EditItemTemplate>
                                <ItemTemplate>
                                    <asp:Label ID="tbNombre" runat="server" Text='<%# Bind("nombre_ma") %>'></asp:Label>
                                </ItemTemplate>
                            </asp:TemplateField>
                        </Columns>
                    </asp:GridView>
                </td>
                <td class="auto-style14"></td>
                <td class="auto-style15" id="grdMarcas"></td>
            </tr>
            <tr>
                <td class="auto-style11">&nbsp; </td>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style8">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style2">
                    &nbsp;</td>
                <td class="auto-style8">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style2">
                    <asp:Button ID="btnGestoria" runat="server" OnClick="Button1_Click" Text="volver al menu anterior" />
                </td>
                <td class="auto-style8">&nbsp;</td>
            </tr>
            <tr>
                <td class="auto-style11">&nbsp;</td>
                <td class="auto-style2">&nbsp;</td>
                <td class="auto-style8">&nbsp;</td>
            </tr>
        </table>
        <div>
        </div>
    </form>
</body>
</html>
